name:                practice
version:             0.1.0.0
license:             BSD3
copyright:           "No license"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            app

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - aeson
  - http-client
  - monad-logger
  - mtl
  - persistent
  - persistent-postgresql
  - servant-server
  - text
  - wai
  - wai-extra
  - warp

executables:
  practice-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - practice
    - monad-logger
    - persistent-postgresql
    - warp


tests:
  practice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - practice
